#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
readonly repo_root
cd "$repo_root"

scripts/test/quick.sh
go test -race ./...
go test -count=1 ./...
go test -run Integration -count=1 ./...
go test -run Crash -count=1 ./...
go test -run Stress -count=20 ./...
